version: '3.8'

services:
  app:
    image: node:18-alpine
    working_dir: /
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["sh", "-c", "cd app && npm install && npm start"]
    environment:
      - NODE_ENV=development
